on:
  schedule:
    - cron: '0 7 * * *' # 每天早上7点执行
  push:
    branches:    
      - main
    paths:
      - data/**.json
  workflow_dispatch:

name: Schedule Update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        
      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          
      - run: pnpm install
      
      - name: Run script
        run: pnpm run update
