name: Schedule Update

on:
  schedule:
    - cron: '0 7 * * *' # 每天早上7点执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Run script
        run: pnpm run update

      - name: Check status and commit changes
        run: |
          git config --global user.name "FuBaooo"
          git config --global user.email "baihe2233@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update almanac cache"
